spring:
  datasource:
    url: "${spring.postgres.baseurl}${spring.postgres.schema}"
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000    # 10 minutes in milliseconds
      max-lifetime: 1800000   # 30 minutes in milliseconds
      pool-name: HikariPool-1

  jpa:
    hibernate:
      ddl-auto: update      # Update the schema automatically during development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
