spring:
  application:
    name: patient-service
  profiles:
    active: dev  # Default profile; can be overridden
  postgres:
    schema: "postgres"
    baseurl: "jdbc:postgresql://localhost:5432/"

logging:
  level:
#    root: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"